### ISSUE TITLE
queries: bigtables: can provide incorrect query results

### ISSUE THREAD

**Issue by dreddshift** [Soostone/aws-redshift#1]
Here is a better query to monitor table size.

select trim(pgdb.datname) as Database, 
	trim(a.name) as Table,  ((b.mbytes/part.total::decimal)*100)::decimal(5,2) as pct_of_total, b.mbytes, b.unsorted_mbytes
	from stv_tbl_perm a 
	join pg_database as pgdb on pgdb.oid = a.db_id
	join (select tbl, sum(decode(unsorted, 1, 1, 0)) as unsorted_mbytes, count(*) as mbytes 
	from stv_blocklist group by tbl) b on a.id=b.tbl
	join ( select sum(capacity) as  total
	  from stv_partitions where part_begin=0 ) as part on 1=1
	where a.slice=0
	order by 3 desc, db_id, name;

**Comment by mightybyte** [comment]
Cool, thanks!  For the benefit of anyone else running across this issue, I had to make two changes to this query to make it work:

s/100/*100/
s/count()/count(*)/
